version: '3.4'

services:
  agilistaapi:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings:DB_Conn
    ports:
      - 81:80
    depends_on:
      - migration
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "P@ssword1"
      ACCEPT_EULA: "Y" 
    ports:
      - "1620:1433" 
  migration:
    image: flyway/flyway
    container_name: flyway_migration_julie
    volumes:
    - ./flyway/sql:/flyway/sql
    entrypoint: ["flyway"]      
    command: -connectRetries=20 -url=jdbc:sqlserver://db;database=master -user=sa -password=P@ssword1 -mixed=true migrate
    depends_on:
      - db